
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMA CREATE DATABASE ENTERO EXISTS ID IF IGUAL INHERITS INTEGER MODE NOT OR OWNER PAR_A PAR_C PTCOMA REPLACE TABLEinit            : instruccionesinstrucciones    : instrucciones instruccioninstrucciones    : instruccion instruccion      : create_Table\n                        | createDB_insrtcreate_Table :  CREATE TABLE ID PAR_A cuerpo_createTable_lista PAR_C PTCOMA\n                       | CREATE TABLE ID PAR_A cuerpo_createTable_lista PAR_C opcion_herencia PTCOMA  cuerpo_createTable_lista : cuerpo_createTable_lista COMA cuerpo_createTable cuerpo_createTable_lista : cuerpo_createTable cuerpo_createTable : ID INTEGER opcion_herencia :  INHERITS PAR_A ID PAR_C createDB_insrt : CREATE DATABASE ID PTCOMAcreateDB_insrt : CREATE OR REPLACE DATABASE ID PTCOMAcreateDB_insrt : CREATE DATABASE IF NOT EXISTS ID PTCOMAcreateDB_insrt : CREATE OR REPLACE DATABASE IF NOT EXISTS ID PTCOMAcreateDB_insrt : CREATE DATABASE ID createDB_unParam PTCOMAcreateDB_insrt : CREATE OR REPLACE DATABASE ID createDB_unParam PTCOMAcreateDB_insrt : CREATE DATABASE IF NOT EXISTS ID createDB_unParam PTCOMAcreateDB_insrt : CREATE OR REPLACE DATABASE IF NOT EXISTS ID createDB_unParam PTCOMAcreateDB_unParam : OWNER IDcreateDB_unParam : MODE ENTEROcreateDB_unParam : OWNER IGUAL IDcreateDB_unParam : MODE IGUAL ENTEROcreateDB_insrt : CREATE DATABASE ID createDB_dosParam PTCOMAcreateDB_insrt : CREATE OR REPLACE DATABASE ID createDB_dosParam PTCOMAcreateDB_insrt : CREATE DATABASE IF NOT EXISTS ID createDB_dosParam PTCOMAcreateDB_insrt : CREATE OR REPLACE DATABASE IF NOT EXISTS ID createDB_dosParam PTCOMAcreateDB_dosParam : OWNER ID MODE ENTEROcreateDB_dosParam : OWNER ID MODE IGUAL ENTEROcreateDB_dosParam : MODE ENTERO OWNER IDcreateDB_dosParam : MODE ENTERO OWNER IGUAL IDcreateDB_dosParam : OWNER IGUAL ID MODE ENTEROcreateDB_dosParam : OWNER IGUAL ID MODE IGUAL ENTEROcreateDB_dosParam : MODE IGUAL ENTERO OWNER IDcreateDB_dosParam : MODE IGUAL ENTERO OWNER IGUAL ID'
    
_lr_action_items = {'CREATE':([0,2,3,4,5,7,16,26,27,43,47,57,60,61,63,71,72,77,81,82,],[6,6,-3,-4,-5,-2,-12,-16,-24,-13,-6,-14,-17,-25,-7,-18,-26,-15,-19,-27,]),'$end':([1,2,3,4,5,7,16,26,27,43,47,57,60,61,63,71,72,77,81,82,],[0,-1,-3,-4,-5,-2,-12,-16,-24,-13,-6,-14,-17,-25,-7,-18,-26,-15,-19,-27,]),'TABLE':([6,],[8,]),'DATABASE':([6,14,],[9,22,]),'OR':([6,],[10,]),'ID':([8,9,15,19,22,29,32,37,40,55,56,62,64,69,],[11,12,23,28,33,39,42,23,54,68,70,73,74,76,]),'IF':([9,22,],[13,34,]),'REPLACE':([10,],[14,]),'PAR_A':([11,49,],[15,64,]),'PTCOMA':([12,17,18,28,30,33,36,39,41,42,44,45,48,51,54,58,59,65,67,68,70,73,75,76,78,79,80,],[16,26,27,-20,-21,43,47,-22,-23,57,60,61,63,-28,-30,71,72,-29,-32,-31,-34,77,-33,-35,81,82,-11,]),'OWNER':([12,30,33,41,42,73,],[19,40,19,56,19,19,]),'MODE':([12,28,33,39,42,73,],[20,38,20,53,20,20,]),'NOT':([13,34,],[21,46,]),'IGUAL':([19,20,38,40,53,56,],[29,31,52,55,66,69,]),'ENTERO':([20,31,38,52,53,66,],[30,41,51,65,67,75,]),'EXISTS':([21,46,],[32,62,]),'INTEGER':([23,],[35,]),'PAR_C':([24,25,35,50,74,],[36,-9,-10,-8,80,]),'COMA':([24,25,35,50,],[37,-9,-10,-8,]),'INHERITS':([36,],[49,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'instrucciones':([0,],[2,]),'instruccion':([0,2,],[3,7,]),'create_Table':([0,2,],[4,4,]),'createDB_insrt':([0,2,],[5,5,]),'createDB_unParam':([12,33,42,73,],[17,44,58,78,]),'createDB_dosParam':([12,33,42,73,],[18,45,59,79,]),'cuerpo_createTable_lista':([15,],[24,]),'cuerpo_createTable':([15,37,],[25,50,]),'opcion_herencia':([36,],[48,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> instrucciones','init',1,'p_init','gramatica.py',103),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones_lista','gramatica.py',107),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones_instruccion','gramatica.py',112),
  ('instruccion -> create_Table','instruccion',1,'p_instruccion','gramatica.py',116),
  ('instruccion -> createDB_insrt','instruccion',1,'p_instruccion','gramatica.py',117),
  ('create_Table -> CREATE TABLE ID PAR_A cuerpo_createTable_lista PAR_C PTCOMA','create_Table',7,'p_create_Table','gramatica.py',121),
  ('create_Table -> CREATE TABLE ID PAR_A cuerpo_createTable_lista PAR_C opcion_herencia PTCOMA','create_Table',8,'p_create_Table','gramatica.py',122),
  ('cuerpo_createTable_lista -> cuerpo_createTable_lista COMA cuerpo_createTable','cuerpo_createTable_lista',3,'p_cuerpo_createTable_lista','gramatica.py',129),
  ('cuerpo_createTable_lista -> cuerpo_createTable','cuerpo_createTable_lista',1,'p_cuerpo_createTable','gramatica.py',134),
  ('cuerpo_createTable -> ID INTEGER','cuerpo_createTable',2,'p_cuerpo_createTable_lista_','gramatica.py',138),
  ('opcion_herencia -> INHERITS PAR_A ID PAR_C','opcion_herencia',4,'p_herencia','gramatica.py',142),
  ('createDB_insrt -> CREATE DATABASE ID PTCOMA','createDB_insrt',4,'p_createDB','gramatica.py',155),
  ('createDB_insrt -> CREATE OR REPLACE DATABASE ID PTCOMA','createDB_insrt',6,'p_createDB_wRP','gramatica.py',158),
  ('createDB_insrt -> CREATE DATABASE IF NOT EXISTS ID PTCOMA','createDB_insrt',7,'p_createDB_wIfNot','gramatica.py',161),
  ('createDB_insrt -> CREATE OR REPLACE DATABASE IF NOT EXISTS ID PTCOMA','createDB_insrt',9,'p_createDB_wRP_wIN','gramatica.py',164),
  ('createDB_insrt -> CREATE DATABASE ID createDB_unParam PTCOMA','createDB_insrt',5,'p_createDB_up','gramatica.py',170),
  ('createDB_insrt -> CREATE OR REPLACE DATABASE ID createDB_unParam PTCOMA','createDB_insrt',7,'p_createDB_wRP_up','gramatica.py',173),
  ('createDB_insrt -> CREATE DATABASE IF NOT EXISTS ID createDB_unParam PTCOMA','createDB_insrt',8,'p_createDB_wIfNot_up','gramatica.py',176),
  ('createDB_insrt -> CREATE OR REPLACE DATABASE IF NOT EXISTS ID createDB_unParam PTCOMA','createDB_insrt',10,'p_createDB_wRP_wIN_up','gramatica.py',179),
  ('createDB_unParam -> OWNER ID','createDB_unParam',2,'p_createDB_unParam_Owner','gramatica.py',182),
  ('createDB_unParam -> MODE ENTERO','createDB_unParam',2,'p_createDB_un_Param_Mode','gramatica.py',185),
  ('createDB_unParam -> OWNER IGUAL ID','createDB_unParam',3,'p_createDB_unParam_Owner_I','gramatica.py',188),
  ('createDB_unParam -> MODE IGUAL ENTERO','createDB_unParam',3,'p_createDB_un_Param_Mode_I','gramatica.py',191),
  ('createDB_insrt -> CREATE DATABASE ID createDB_dosParam PTCOMA','createDB_insrt',5,'p_createDB_dp','gramatica.py',199),
  ('createDB_insrt -> CREATE OR REPLACE DATABASE ID createDB_dosParam PTCOMA','createDB_insrt',7,'p_createDB_wRP_dp','gramatica.py',202),
  ('createDB_insrt -> CREATE DATABASE IF NOT EXISTS ID createDB_dosParam PTCOMA','createDB_insrt',8,'p_createDB_wIfNot_dp','gramatica.py',205),
  ('createDB_insrt -> CREATE OR REPLACE DATABASE IF NOT EXISTS ID createDB_dosParam PTCOMA','createDB_insrt',10,'p_createDB_wRP_wIN_dp','gramatica.py',208),
  ('createDB_dosParam -> OWNER ID MODE ENTERO','createDB_dosParam',4,'p_createDB_dosParam_Owner','gramatica.py',211),
  ('createDB_dosParam -> OWNER ID MODE IGUAL ENTERO','createDB_dosParam',5,'p_createDB_dosParam_Owner_b','gramatica.py',214),
  ('createDB_dosParam -> MODE ENTERO OWNER ID','createDB_dosParam',4,'p_createDB_dosParam_Mode','gramatica.py',217),
  ('createDB_dosParam -> MODE ENTERO OWNER IGUAL ID','createDB_dosParam',5,'p_createDB_dosParam_Mode_b','gramatica.py',220),
  ('createDB_dosParam -> OWNER IGUAL ID MODE ENTERO','createDB_dosParam',5,'p_createDB_dosParam_Owner_I','gramatica.py',223),
  ('createDB_dosParam -> OWNER IGUAL ID MODE IGUAL ENTERO','createDB_dosParam',6,'p_createDB_dosParam_Owner_I_b','gramatica.py',226),
  ('createDB_dosParam -> MODE IGUAL ENTERO OWNER ID','createDB_dosParam',5,'p_createDB_dosParam_Mode_I','gramatica.py',229),
  ('createDB_dosParam -> MODE IGUAL ENTERO OWNER IGUAL ID','createDB_dosParam',6,'p_createDB_dosParam_Mode_I_b','gramatica.py',232),
]
