
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMA CREATE ID INHERITS INTEGER PAR_A PAR_C PTCOMA TABLEinit            : instruccionesinstrucciones    : instrucciones instruccioninstrucciones    : instruccion instruccion      : create_Tablecreate_Table :  CREATE TABLE ID PAR_A cuerpo_createTable_lista PAR_C PTCOMA\n                       | CREATE TABLE ID PAR_A cuerpo_createTable_lista PAR_C opcion_herencia PTCOMA  cuerpo_createTable_lista : cuerpo_createTable_lista COMA cuerpo_createTable cuerpo_createTable_lista : cuerpo_createTable cuerpo_createTable : ID INTEGER opcion_herencia :  INHERITS PAR_A ID PAR_C '
    
_lr_action_items = {'CREATE':([0,2,3,4,6,16,20,],[5,5,-3,-4,-2,-5,-6,]),'$end':([1,2,3,4,6,16,20,],[0,-1,-3,-4,-2,-5,-6,]),'TABLE':([5,],[7,]),'ID':([7,9,15,21,],[8,10,10,22,]),'PAR_A':([8,18,],[9,21,]),'INTEGER':([10,],[13,]),'PAR_C':([11,12,13,19,22,],[14,-8,-9,-7,23,]),'COMA':([11,12,13,19,],[15,-8,-9,-7,]),'PTCOMA':([14,17,23,],[16,20,-10,]),'INHERITS':([14,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'instrucciones':([0,],[2,]),'instruccion':([0,2,],[3,6,]),'create_Table':([0,2,],[4,4,]),'cuerpo_createTable_lista':([9,],[11,]),'cuerpo_createTable':([9,15,],[12,19,]),'opcion_herencia':([14,],[17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> instrucciones','init',1,'p_init','gramatica.py',95),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones_lista','gramatica.py',99),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones_instruccion','gramatica.py',105),
  ('instruccion -> create_Table','instruccion',1,'p_instruccion','gramatica.py',109),
  ('create_Table -> CREATE TABLE ID PAR_A cuerpo_createTable_lista PAR_C PTCOMA','create_Table',7,'p_create_Table','gramatica.py',113),
  ('create_Table -> CREATE TABLE ID PAR_A cuerpo_createTable_lista PAR_C opcion_herencia PTCOMA','create_Table',8,'p_create_Table','gramatica.py',114),
  ('cuerpo_createTable_lista -> cuerpo_createTable_lista COMA cuerpo_createTable','cuerpo_createTable_lista',3,'p_cuerpo_createTable_lista','gramatica.py',122),
  ('cuerpo_createTable_lista -> cuerpo_createTable','cuerpo_createTable_lista',1,'p_cuerpo_createTable','gramatica.py',127),
  ('cuerpo_createTable -> ID INTEGER','cuerpo_createTable',2,'p_cuerpo_createTable_lista_','gramatica.py',131),
  ('opcion_herencia -> INHERITS PAR_A ID PAR_C','opcion_herencia',4,'p_herencia','gramatica.py',135),
]
