<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <createDB_insrt>
 
<createDB_insrt> ::= CREATE DATABASE ID PTCOMA
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <createDB_insrt>
 
<createDB_insrt> ::= CREATE DATABASE ID PTCOMA
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <createDB_insrt>
 
<createDB_insrt> ::= CREATE DATABASE ID PTCOMA
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <createDB_insrt>
 
<createDB_insrt> ::= CREATE DATABASE ID PTCOMA