<inicio> ::= <codigo>
 
<codigo> ::= <instrucciones_globales_list>
 
<instrucciones_globales_list> ::= <instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<use_database_instr> ::= USE ID PTCOMA
 
<inicio> ::= <codigo>
 
<codigo> ::= <instrucciones_globales_list>
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createDB_insrt> ::= CREATE DATABASE ID PTCOMA
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createDB_insrt> ::= CREATE DATABASE ID PTCOMA
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_globales_list> ::= <instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createDB_insrt> ::= CREATE DATABASE ID PTCOMA