<inicio> ::= <codigo>
 
<codigo> ::= <instrucciones_globales_list>
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<alterindex_insrt> ::= ALTER INDEX ID ALTER ID <opcionIndex> PTCOMA
 
<lista_drop_id_index> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<alterindex_insrt> ::= ALTER INDEX ID ALTER ID <opcionIndex> PTCOMA
 
<lista_drop_id_index> ::= ID
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createIndex> ::= CREATE INDEX ID ON ID <opc_index> PTCOMA
 
<opc_index> ::= PARA <opc_index_par> PARC
 
<opc_index_par> ::= <campos_c> 
 
<campos_c> ::= <campos_c> COMA ID
 
<campos_c> ::= ID
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createIndex> ::= CREATE INDEX ID ON ID <opc_index> PTCOMA
 
<opc_index> ::= PARA <opc_index_par> PARC
 
<opc_index_par> ::= <campos_c> 
 
<campos_c> ::= <campos_c> COMA ID
 
<campos_c> ::= ID
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createIndex> ::= CREATE INDEX ID ON ID <opc_index> PTCOMA
 
<opc_index> ::= PARA <opc_index_par> PARC
 
<opc_index_par> ::= <campos_c> 
 
<campos_c> ::= ID
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<create_Table_isnrt> ::= CREATE TABLE ID PAR_A <cuerpo_createTable_lista> PAR_C PTCOMA 
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF>
 
<TIPO_DATO_DEF> ::= VARCHAR PARA ENTERO PARC
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF>
 
<TIPO_DATO_DEF> ::= VARCHAR PARA ENTERO PARC
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF>
 
<TIPO_DATO_DEF> ::= INTEGER
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<use_database_instr> ::= USE ID PTCOMA
 
<instrucciones_globales_list> ::= <instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createDB_insrt> ::= CREATE DATABASE ID PTCOMA